"""
M1 — Structured Ticket Parsing

Defines the SupportTicket contract that every downstream agent
will consume instead of raw customer text.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, field_validator


# Restrict channel to known values.
class Channel(str, Enum):
    CHAT = "chat"
    EMAIL = "email"


# Standardized issue categories used throughout the system.
class IssueType(str, Enum):
    REFUND_REQUEST = "refund_request"
    RETURN_REQUEST = "return_request"
    SHIPPING_STATUS = "shipping_status"
    WARRANTY_CLAIM = "warranty_claim"
    ORDER_STATUS = "order_status"
    COMPLAINT = "complaint"
    GENERAL_POLICY_QUESTION = "general_policy_question"
    OTHER = "other"


class Sentiment(str, Enum):
    POSITIVE = "positive"
    NEUTRAL = "neutral"
    NEGATIVE = "negative"
    ANGRY = "angry"


class Urgency(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class SupportTicket(BaseModel):
    """Validated ticket object produced by the Triage Agent."""

    # Metadata provided by the application.
    ticket_id: str
    channel: Channel
    customer_id: str

    # Original customer message.
    raw_text: str = Field(
        ...,
        description="Original, unmodified ticket text"
    )

    # Information extracted by the AI.
    issue_type: IssueType

    # Optional because not every ticket refers to an order.
    order_id: Optional[str] = Field(
        default=None,
        description="Referenced order ID, if any"
    )

    sentiment: Sentiment
    urgency: Urgency

    # One-line neutral summary generated by the model.
    summary: str = Field(
        ...,
        description="One-sentence neutral summary of the customer's request"
    )

    # AI safety signal.
    suspected_prompt_injection: bool = Field(
        default=False,
        description="True if the message attempts to manipulate the AI."
    )

    # Model confidence (must be between 0 and 1).
    extraction_confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Model confidence score"
    )

    # Automatically populated when the object is created.
    parsed_at: datetime = Field(default_factory=datetime.utcnow)

    @field_validator("ticket_id", "customer_id")
    @classmethod
    def not_blank(cls, value: str) -> str:
        """Ensure required IDs are not empty or whitespace."""

        if not value or not value.strip():
            raise ValueError("must not be blank")

        return value